version: "3.8"
services:
  web:
    image: 777dreammaster/counter
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hitcount
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: